### ISSUE TITLE
Error generator-typescript-backbone-amd

### ISSUE THREAD

**Issue by paninRadario** [erosb/generator-typescript-backbone-amd#5]
I'm install prerequisites and generator-typescript-backbone-amd. But when I can scaffold my project, using the `yo typescript-backbone-amd command`
I have error:
`events.js:141
      throw er; // Unhandled 'error' event
      ^
 AssertionError: Trying to copy from a source that does not exist: C:\Users\Panin\AppData\Roaming\npm\node_modules\generator-typescript-backbone-amd\app\templates\.gitignore
    at EditionInterface.exports._copySingle (C:\Users\Panin\AppData\Roaming\npm\node_modules\generator-typescript-backbone-amd\node_modules\mem-fs-editor\actions\copy.js:45:3)`

**Comment by paninRadario** [comment]
I'm insert my empty .gitignore file and yeoman begin work.

**Comment by erosb** [comment]
Hello, I couldn't really reproduce the issue locally. Probably it means that the .gitignore file is missing only after npm installation. Anyway, I hope 914dcd480ab031dffa74165d6c1ab1f08f13fc9b will solve it.

Do you need a release tag to test it?

**Comment by paninRadario** [comment]
No, thanks, but maybe you need additional its solution in Github README.md. 
TypeScript becoming popular in webDev.
