### ISSUE TITLE
error out of box

### ISSUE THREAD

**Issue by bp1977** [erosb/generator-typescript-backbone-amd#7]
brian@DUBHOMEPC C:\Users\brian\Source\messing
> mkdir typescript-backbone-amd

brian@DUBHOMEPC C:\Users\brian\Source\messing
> yo typescript-backbone-amd
Initializing npm package...
events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: Arguments to path.resolve must be strings
    at Object.win32.resolve (path.js:146:13)
    at module.exports.generators.Base.extend.initNpmPackage (C:\Users\brian\AppData\Roaming\npm\node_modules\generator-typescript-backbone-amd\app\index.js:27:27)
    at C:\Users\brian\AppData\Roaming\npm\node_modules\generator-typescript-backbone-amd\node_modules\yeoman-generator\lib\base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:358:17)

brian@DUBHOMEPC C:\Users\brian\Source\messing
> cd typescript-backbone-amd

brian@DUBHOMEPC C:\Users\brian\Source\messing\typescript-backbone-amd
> yo typescript-backbone-amd

     _-----_
    |       |    .------------------------------------------.
    |--(o)--|    | Update available: 1.7.0 (current: 1.6.0) |
   `---------´   |     Run npm install -g yo to update.     |
    ( _´U`_ )    '------------------------------------------'
    /___A___\
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

Initializing npm package...
events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: Arguments to path.resolve must be strings
    at Object.win32.resolve (path.js:146:13)
    at module.exports.generators.Base.extend.initNpmPackage (C:\Users\brian\AppData\Roaming\npm\node_modules\generator-typescript-backbone-amd\app\index.js:27:27)
    at C:\Users\brian\AppData\Roaming\npm\node_modules\generator-typescript-backbone-amd\node_modules\yeoman-generator\lib\base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:358:17)

brian@DUBHOMEPC C:\Users\brian\Source\messing\typescript-backbone-amd

**Comment by erosb** [comment]
@bp1977 could you please test it with the HEAD revision? Or do you need a new NPM release for it?

Thanks

**Comment by bp1977** [comment]
Sorry for being so slow to come back. Im not sure what you mean by " HEAD revision".

I reinstalled all deps listed in the readme. Still getting same error.



npm info install generator-typescript-backbone-amd@0.0.3
npm info postinstall generator-typescript-backbone-amd@0.0.3
npm verb unlock done using C:\Users\brian\AppData\Roaming\npm-cache\_locks\generator-typescript-bac-e1628e3aeeeea44a.lock for C:\Users\brian\AppData\Roaming\npm\node_modules\generator-typescript-backbone-amd
generator-typescript-backbone-amd@0.0.3 C:\Users\brian\AppData\Roaming\npm\node_modules\generator-typescript-backbone-amd
├── init-package-json@1.9.3 (read@1.0.7, validate-npm-package-name@2.2.2, promzard@0.3.0, semver@5.1.0, validate-npm-package-license@3.0.1, npm-package-arg@4.1.0, glob@6.0.4, read-package-json@2.0.3)
└── yeoman-generator@0.20.3 (read-chunk@1.0.1, detect-conflict@1.0.0, path-exists@1.0.0, yeoman-welcome@1.0.1, path-is-absolute@1.0.0, yeoman-assert@2.1.1, text-table@0.2.0, user-home@2.0.0, xdg-basedir@2.0.0, dargs@4.1.0, class-extend@0.1.2, mime@1.3.4, istextorbinary@1.0.2, debug@2.2.0, run-async@0.1.0, nopt@3.0.6, chalk@1.1.1, async@1.5.2, mkdirp@0.5.1, shelljs@0.5.3, cli-table@0.3.1, glob@5.0.15, through2@2.0.1, rimraf@2.5.2, findup-sync@0.2.1, diff@2.2.1, mem-fs-editor@2.2.0, pretty-bytes@2.0.1, github-username@2.1.0, dateformat@1.0.12, cross-spawn@2.1.5, underscore.string@3.3.4, download@4.4.3, yeoman-environment@1.5.2, gruntfile-editor@1.1.0, html-wiring@1.2.0, sinon@1.17.3, lodash@3.10.1, inquirer@0.8.5)
npm verb exit [ 0, true ]
npm info ok

C:\Users\brian\Source\typescript-backbone-amd>dir
 Volume in drive C has no label.
 Volume Serial Number is F212-F576

 Directory of C:\Users\brian\Source\typescript-backbone-amd

10/03/2016  05:26    <DIR>          .
10/03/2016  05:26    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  284,395,765,760 bytes free

C:\Users\brian\Source\typescript-backbone-amd>yo typescript-backbone-amd:app
Initializing npm package...
events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: Arguments to path.resolve must be strings
    at Object.win32.resolve (path.js:146:13)
    at module.exports.generators.Base.extend.initNpmPackage (C:\Users\brian\AppData\Roaming\npm\node_modules\generator-typescript-backbone-amd\app\index.js:27:27)
    at C:\Users\brian\AppData\Roaming\npm\node_modules\generator-typescript-backbone-amd\node_modules\yeoman-generator\lib\base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:358:17)

C:\Users\brian\Source\typescript-backbone-amd>yo typescript-backbone-amd
Initializing npm package...
events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: Arguments to path.resolve must be strings
    at Object.win32.resolve (path.js:146:13)
    at module.exports.generators.Base.extend.initNpmPackage (C:\Users\brian\AppData\Roaming\npm\node_modules\generator-typescript-backbone-amd\app\index.js:27:27)
    at C:\Users\brian\AppData\Roaming\npm\node_modules\generator-typescript-backbone-amd\node_modules\yeoman-generator\lib\base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by erosb** [comment]
@bp1977 I've just released 0.0.4 on npm, please test it.

Thanks.

**Comment by bp1977** [comment]
Fixed , thanks. I'll study it closly later. It has a lot pf features I was struggling to get started with. typescrpt, require, tests and gulp mostly.



10/03/2016  08:56    <DIR>          .
10/03/2016  08:56    <DIR>          ..
10/03/2016  08:54               122 .bowerrc
10/03/2016  08:54                81 .gitignore
10/03/2016  08:54               481 bower.json
10/03/2016  08:54             1,522 gulpfile.js
10/03/2016  08:54               201 index.html
10/03/2016  08:54    <DIR>          js
10/03/2016  08:56    <DIR>          node_modules
10/03/2016  08:54               539 package.json
10/03/2016  08:54    <DIR>          src
10/03/2016  08:54               343 test.html
10/03/2016  08:54               559 tsconfig.json
10/03/2016  08:54               760 tsd.json
               9 File(s)          4,608 bytes
